
// export const roles = {
//   "Admin for test role": [
//     '/',
//     '/booking',
//     '/booking/create_new_booking',
//     '/booking/update_lot_status',
//     '/booking/payment',
//     '/booking/lot_list',
//     '/product_management/product',
//     '/product_management/custom_charge',
//     "/product_management/location_status",
//     '/payment/payment_history',
//     '/challan/create_challan',
//     "/challan/challan_lot",
//     '/challan/challan_history',
//     '/tracking',
//     '/shipments', "/shipments/addLot", '/shipments/updateStatus',
//     '/customers',
//     "/users",
//     "/branches",
//     '/officeExpense/officeExpenses',
//     '/officeExpense/officeExpense_category',
//     '/settings/company-meta-info-list',
//     '/booking/location-status-list',
//     // '/booking/branch-list',
//     '/user-list',
//   ],
//   "Country Admin for test role": [
//     '/',
//     '/booking',
//     '/booking/create_new_booking',
//     '/booking/update_lot_status',
//     '/booking/payment',
//     '/booking/lot_list',
//     '/product_management/product',
//     '/product_management/custom_charge',
//     "/product_management/location_status",
//     '/payment/payment_history',
//     '/challan/create_challan', "/challan/challan_lot",
//     '/challan/challan_history',
//     '/tracking',
//     '/shipments', "/shipments/addLot", '/shipments/updateStatus',
//     '/customers',
//     "/users",
//     "/branches",
//     '/officeExpense/officeExpenses',
//     '/officeExpense/officeExpense_category',
//     '/settings/company-meta-info-list',
//     '/booking/location-status-list',
//     '/booking/branch_list',
//   ],
//   'Booking Manager for test role': [
//     '/',
//     '/booking',
//     '/booking/create_new_booking',
//     '/booking/update_lot_status',
//     '/booking/payment',
//     '/booking/lot_list',
//     '/product_management/product',
//     '/product_management/custom_charge',
//     '/payment/payment_history',
//     // '/payment/conversion_Rate',
//     '/challan/create_challan', "/challan/challan_lot",
//     '/challan/challan_history',
//     '/tracking',
//     '/shipments', '/shipments/updateStatus',
//     "/shipments/addLot",
//     '/customers',
//     '/officeExpense/officeExpenses',
//     '/officeExpense/officeExpense_category',
//     '/settings/company-meta-info-list',
//   ],
//   'Package Controller for test': [
//     '/',
//     '/booking',
//     '/booking/create_new_booking',
//     '/booking/lot_list',
//     '/booking/update_lot_status',
//     '/booking/payment',
//     '/payment/payment_history',
//     '/challan/create_challan', "/challan/challan_lot",
//     '/challan/challan_history',

//     '/tracking',
//     '/shipments',
//     "/shipments/addLot", '/shipments/updateStatus',
//     '/customers',
//     '/officeExpense/officeExpenses',
//     '/officeExpense/officeExpense_category',
//     '/settings/company-meta-info-list',
//   ],
//   "Staff  for test role": [
//     '/',
//     '/booking',
//     '/booking/create_new_booking',
//     '/booking/lot_list',
//     '/challan/create_challan',
//     '/challan/challan_history',
//     "/challan/challan_lot",
//     '/tracking',
//     '/shipments',
//     "/shipments/addLot",
//   ],
//   "Delivery Man for test role": [
//     '/',
//     '/booking',
//     '/booking/create_new_booking',
//     '/booking/lot_list',
//     '/booking/update_lot_status',
//     '/booking/payment',
//     '/payment/payment_history',
//     '/challan/create_challan',
//     "/challan/challan_lot",
//     '/challan/challan_history',

//     '/tracking',
//     '/shipments', '/shipments/updateStatus',
//     "/shipments/addLot"


//   ],
// }









export const roles = {
  "Admin": [
    '/',
    '/booking',
    '/booking/create_new_booking',
    '/booking/update_lot_status',
    '/booking/payment',
    '/booking/lot_list',
    '/product_management/product',
    '/product_management/custom_charge',
    "/product_management/location_status",
    '/payment/payment_history',
    '/challan/create_challan',
    '/challan/challan_history', '/challan/challan_lot',
    '/tracking',
    '/shipments',
    '/customers',
    "/users",
    "/branches",
    '/officeExpense/officeExpenses',
    '/officeExpense/officeExpense_category',
    '/settings/company-meta-info-list',
    '/booking/location-status-list',
    // '/booking/branch-list',
    '/user-list',
  ],
  "Country Admin": [
    '/',
    '/booking',
    '/booking/create_new_booking',
    '/booking/update_lot_status',
    '/booking/payment',
    '/booking/lot_list',
    '/product_management/product',
    '/product_management/custom_charge',
    "/product_management/location_status",
    '/payment/payment_history',
    '/challan/create_challan',
    '/challan/challan_history', '/challan/challan_lot',
    '/tracking',
    '/shipments',
    '/customers',
    "/users",
    "/branches",
    '/officeExpense/officeExpenses',
    '/officeExpense/officeExpense_category',
    '/settings/company-meta-info-list',
    '/booking/location-status-list',
    '/booking/branch_list',
  ],
  'Booking Manager': [
    '/',
    '/booking',
    '/booking/create_new_booking',
    '/booking/update_lot_status',
    '/booking/payment',
    '/booking/lot_list',
    '/product_management/product',
    '/product_management/custom_charge',
    '/payment/payment_history',
    // '/payment/conversion_Rate',
    '/challan/create_challan',
    '/challan/challan_history',
    '/challan/challan_lot',

    '/tracking',
    '/shipments', '/shipments/updateStatus',
    "/shipments/addLot",
    '/customers',
    '/officeExpense/officeExpenses',
    '/officeExpense/officeExpense_category',
    '/settings/company-meta-info-list',
  ],
  'Package Controller': [
    '/',
    '/booking',
    '/booking/create_new_booking',
    '/booking/lot_list',
    '/booking/update_lot_status',
    '/booking/payment',
    '/payment/payment_history',
    '/challan/create_challan',
    '/challan/challan_history',

    '/tracking',
    '/shipments',
    '/customers',
    '/officeExpense/officeExpenses',
    '/officeExpense/officeExpense_category',
    '/settings/company-meta-info-list',
  ],
  "Staff": [
    '/booking',
    '/booking/create_new_booking',
    '/booking/lot_list',
    '/challan/create_challan',
    '/challan/challan_history',

    '/tracking',
    '/shipments',
  ],
  "Delivery Man": [
    '/',
    '/booking',
    '/booking/create_new_booking',
    '/booking/lot_list',
    '/booking/update_lot_status',
    '/booking/payment',
    '/payment/payment_history',
    '/challan/create_challan',
    '/challan/challan_history',
    '/tracking',
    '/shipments',


  ],
}










